require:
  - rubocop
  - rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'vendor/bundle/**/*'
    - 'scripts/add-data.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/conservation_records_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/helpers/in_house_repair_records_helper.rb'
    - 'app/helpers/external_repair_records_helper.rb'
    - 'app/helpers/activity_helper.rb'
    - 'app/controllers/users_controller.rb'
    - 'lib/tasks/batch.rake'
    - 'lib/tasks/export.rake'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/export.rake'

Layout/LineLength:
  Exclude:
    - 'app/views/conservation_records/_conservation_record.json.jbuilder'
    - 'lib/tasks/batch.rake'
    - 'spec/helpers/activity_helper_spec.rb'
    - 'spec/helpers/in_house_repair_records_helper_spec.rb'
    - 'lib/tasks/export.rake'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/search_controller.rb'
    - 'app/controllers/treatment_reports_controller.rb'
    - 'app/models/ability.rb'
    - 'app/helpers/activity_helper.rb'
    - 'app/controllers/users_controller.rb'
    - 'lib/tasks/batch.rake'
    - 'app/helpers/in_house_repair_records_helper.rb'
    - 'lib/tasks/export.rake'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/activity_helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/activity_helper.rb'

Rails/EagerEvaluationLogMessage: 
  Exclude:
    - 'config/deploy.rb'

Rails/Exit: 
  Exclude:
    - 'config/deploy/production.rb'
    - 'config/deploy.rb'

Rails/Output:
  Exclude:
    - 'config/deploy/production.rb'
    - 'config/deploy.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'config/puma.rb'
