inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - vendor/bundle/**/*

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'app/views/conservation_records/_conservation_record.json.jbuilder'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/search_controller.rb'
    - 'app/controllers/treatment_reports_controller.rb'
