# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
staging:
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER_NAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 5
  database: <%= ENV['MYSQL_DB'] %>

  <%
  socket = [
  ENV["BOXEN_MYSQL_SOCKET"],
  "/var/run/mysql5/mysqld.sock",
  "/tmp/mysql.sock"
  ].detect { |f| f && File.exist?(f) }

  port = ENV["TREATMENT_DATABASE_PORT"]%>

mysql_connection: &mysql_connection
<% if socket %>
  host: <%= ENV["TREATMENT_DATABASE_HOST"] %>
  socket: <%= socket %>
<% else %>
  host: 127.0.0.1
  port: <%= port %>
<% end %>

database_settings: &database_settings
  <<: *mysql_connection
  adapter:   <%= ENV["TREATMENT_DATABASE_ADAPTER"] %>
  pool:      <%= ENV["TREATMENT_DATABASE_POOL"] %>
  username:  <%= ENV["TREATMENT_DATABASE_USERNAME"] %>
  password:  <%= ENV["TREATMENT_DATABASE_PASSWORD"] %>
  database:  <%= ENV["TREATMENT_DATABASE_NAME"] %>
  host:      <%= ENV["TREATMENT_DATABASE_HOST"] %>
  timeout:   <%= ENV["TREATMENT_DATABASE_TIMEOUT"] %>
  encoding:  utf8
  RECONNECT: FALSE
#
# development:
#   <<: *default
#   database: db/development.sqlite3

development:
  <<: *database_settings

test:
  <<: *database_settings

production:
  <<: *database_settings