# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe StaffCodesController, type: :controller do
  include Devise::Test::ControllerHelpers
  # This should return the minimal set of attributes required to create a valid
  # StaffCode. As you add validations to StaffCode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      code: 'C',
      points: 10
    }
  end

  let(:invalid_attributes) do
    {
      code: nil,
      points: nil
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StaffCodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  def sign_in_user(user)
    sign_in user
  end

  before do
    user = create(:user, role: 'admin')
    sign_in_user(user)
  end

  describe 'GET #index' do
    it 'returns a success response' do
      StaffCode.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      staff_code = StaffCode.create! valid_attributes
      get :show, params: { id: staff_code.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      staff_code = StaffCode.create! valid_attributes
      get :edit, params: { id: staff_code.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new StaffCode' do
        expect do
          post :create, params: { staff_code: valid_attributes }, session: valid_session
        end.to change(StaffCode, :count).by(1)
      end

      it 'redirects to the created staff_code' do
        post :create, params: { staff_code: valid_attributes }, session: valid_session
        expect(response).to redirect_to(StaffCode.last)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { staff_code: invalid_attributes }, session: valid_session
        expect(response).to_not be_successful
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        {
          code: 'C',
          points: 10
        }
      end

      it 'updates the requested staff_code' do
        staff_code = StaffCode.create! valid_attributes
        put :update, params: { id: staff_code.to_param, staff_code: new_attributes }, session: valid_session
        staff_code.reload
        expect(response).to redirect_to(staff_code)
      end

      it 'redirects to the staff_code' do
        staff_code = StaffCode.create! valid_attributes
        put :update, params: { id: staff_code.to_param, staff_code: valid_attributes }, session: valid_session
        expect(response).to redirect_to(staff_code)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        staff_code = StaffCode.create! valid_attributes
        put :update, params: { id: staff_code.to_param, staff_code: invalid_attributes }, session: valid_session
        expect(response).to_not be_successful
      end
    end
  end
end
