on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  upgradeRuby:
    name: "Upgrade Ruby"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Check Ruby Version
        id: check-ruby-version
        run: |
          LATEST_RUBY_VERSION=$(ruby -v | awk '{ print $2 }' | awk -F 'p' '{ print $1 }')
          CURRENT_RUBY_VERSION=$(cat .ruby-version | awk -F '-' '{ print $2 }')

          echo "::set-output name=CURRENT_RUBY_VERSION::${CURRENT_RUBY_VERSION}"
          echo "::set-output name=LATEST_RUBY_VERSION::${LATEST_RUBY_VERSION}"

          if [ "$CURRENT_RUBY_VERSION" = "$LATEST_RUBY_VERSION" ]; then
              echo '::set-output name=RUBY_VERSION_CHANGED::false'
          else
              echo '::set-output name=RUBY_VERSION_CHANGED::true'
              echo "ruby-${LATEST_RUBY_VERSION}" > .ruby-version
              sed -E -i'' -e 's,circleci/ruby:2.7.[0-9]+-node-browsers,'circleci/ruby:${LATEST_RUBY_VERSION}-node-browsers',g' .circleci/config.yml
          fi

      - name: Update Gemfile
        id: update-gemfile
        run: |
          sed -E -i'' -e "s/ruby '2.7.[0-9]+'/ruby '${{ steps.check-ruby-version.outputs.LATEST_RUBY_VERSION }}'/g" Gemfile
          bundle update --ruby
        if: steps.check-ruby-version.outputs.RUBY_VERSION_CHANGED == 'true'

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Upgraded Ruby from ${{ steps.check-ruby-version.outputs.CURRENT_RUBY_VERSION }} to ${{ steps.check-ruby-version.outputs.LATEST_RUBY_VERSION }}"
          delete-branch: true
          title: 'Ruby Upgrade'
          body: |
            # Ruby Upgrade
            - Upgraded from ${{ steps.check-ruby-version.outputs.CURRENT_RUBY_VERSION }} to ${{ steps.check-ruby-version.outputs.LATEST_RUBY_VERSION }}
          labels: |
            ruby upgrade
            automated pr
          assignees: hortongn
          reviewers: hortongn
        if: steps.check-ruby-version.outputs.RUBY_VERSION_CHANGED == 'true'

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pull-request.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pull-request.outputs.pull-request-url }}"
        if: steps.check-ruby-version.outputs.RUBY_VERSION_CHANGED == 'true'